---

- name: install haproxy
  hosts: all
  pre_tasks:
    - name: update repositories cache
      apt:
        update_cache: yes
    - package: name={{ item }} state=latest
      with_items:
        - curl
        - jq
        - iproute
        - rsyslog
        - ca-certificates
        - sudo
        - python-apt
        - software-properties-common
        - tar
        - unzip
        - bzip2
        - gzip
        - git
  roles:
    - role: ansible-haproxy
    - role: entercloudsuite.prometheus-exporter
      prometheus_enable_exporter_config_flags: true
      prometheus_exporter_name: haproxy_exporter
      prometheus_exporter_version: 0.9.0
      prometheus_exporter_config_flags:
        '--haproxy.scrape-uri': 'unix:/run/haproxy/admin.sock'
    - role: entercloudsuite.prometheus-exporter
      prometheus_exporter_name: node_exporter
      prometheus_exporter_version: 0.16.0
    - role: entercloudsuite.consul
      consul_version: 1.4.4
      consul_packer_provision: true
      consul_configs:
        main:
          bind_addr: 0.0.0.0
          client_addr: 0.0.0.0
          node_name: "{{ ansible_hostname }}"
          data_dir: "{{ consul_data_dir }}"
          encrypt: "K8n07GA/ZoANSmJ5zkvgOg=="
          enable_syslog: true
          datacenter: automium
          server: true
          ui: true
  post_tasks:
    - name: add prometheus user to haproxy group
      user:
        name: prometheus
        groups: haproxy
        append: yes

- name: prepare virtualenv
  hosts: all
  tasks:
    - name: create var project path
      set_fact:
        script_path: /usr/src/cloud
    - name: install requirements
      package: name="{{ item }}"
      with_items:
        - libffi-dev
        - libssl-dev
        - python-minimal
        - python-pip
        - virtualenv
    - name: create directory
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ script_path }}"
        - "{{ script_path }}/roles"
    - name: create requirements.txt
      copy:
        content: |
          ansible==2.7.10
          asn1crypto==0.24.0
          bcrypt==3.1.6
          cffi==1.12.3
          cryptography==2.6.1
          enum34==1.1.6
          Jinja2==2.10.1
          MarkupSafe==1.1.1
          paramiko==2.4.2
          pyasn1==0.4.5
          pycparser==2.19
          pycrypto==2.6.1
          PyNaCl==1.3.0
          PyYAML==5.1
          six==1.12.0
          jmespath==0.9.3
        dest: "{{ script_path }}/requirements.txt"
        remote_src: yes
    - name: get current repo and commit
      set_fact:
        repository: "{{ lookup('env','TRAVIS_REPO_SLUG') }}"
        commit: "{{ lookup('env','TRAVIS_COMMIT') }}"
    - name: get current pull request repo and commit
      set_fact:
        repository: "{{ lookup('env','TRAVIS_PULL_REQUEST_SLUG') }}"
        commit: "{{ lookup('env','TRAVIS_PULL_REQUEST_SHA') }}"
      when: lookup('env','TRAVIS_PULL_REQUEST_SLUG') != ""
    - name: create requirements.yml
      copy:
        content: |
          - src: "https://github.com/{{ repository }}"
            version: "{{ commit }}"
          - src: entercloudsuite.consul
            version: 1.0.1
        dest: "{{ script_path }}/requirements.yml"
        remote_src: yes
    - name: install python requirements
      pip:
        requirements: "{{ script_path }}/requirements.txt"
        virtualenv: "{{ script_path }}/venv"
    - name: install ansible roles
      shell: source {{ script_path }}/venv/bin/activate && ansible-galaxy install -f -p roles -r requirements.yml
      args:
        chdir: "{{ script_path }}"
        executable: /bin/bash
    - name: cleanup image
      shell: |
        cloud-init clean -l -s
        rm -rf /var/lib/cloud
        rm -rf /run/cloud-init
        rm -rf /home/ubuntu/.ssh/authorized_keys
        rm -rf /root/.ssh/authorized_keys
      args:
        removes: /var/lib/cloud
